services:
# Uncomment the following lines to run/debug the RetailPortal.Api service in a container
#  retailportal.api:
#    image: ${DOCKER_REGISTRY-}retailportalapi
#    build:
#      context: .
#      dockerfile: Presentation/RetailPortal.Api/Dockerfile
  
  postgres:
    container_name: retailportal-postgres
    image: postgres
    environment:
      POSTGRES_USER: retailportal
      POSTGRES_PASSWORD: retailportal
      POSTGRES_DB: retailportal
    ports:
      - "5432:5432"
#  Run this manually if want to enable postgres logging to all
#  docker exec -it retailportal-postgres /bin/bash
#  echo log_statement = 'all' >> /var/lib/postgresql/data/postgresql.conf
#  restart docker container
#  to verify run this command: cat /var/lib/postgresql/data/postgresql.conf | grep log_statement
  
  
  emulator:
    container_name: "servicebus-emulator"
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    volumes:
      - "/Config.json"
    ports:
      - "5672:5672"
    environment:
      SQL_SERVER: sqledge
      MSSQL_SA_PASSWORD: P@ssw0rd
      ACCEPT_EULA: Y
    depends_on:
      - sqledge
    networks:
      sb-emulator:
        aliases:
          - "sb-emulator"
  sqledge:
    container_name: "sqledge"
    image: "mcr.microsoft.com/azure-sql-edge:latest"
    networks:
      sb-emulator:
        aliases:
          - "sqledge"
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: P@ssw0rd

networks:
  sb-emulator: